import Head from 'next/head'
import Image from 'next/image'
import PictureCard from '@/components/cards/picture/PictureCard'
import { mockPictureCardProps } from '@/components/cards/picture/PictureCard.mocks';
import { mockSidebarLayoutProps } from '@/components/layout/sidebar/SidebarLayout.mocks';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
// import PrimaryLayout from '@/components/layouts/primary/PrimaryLayout';
// import SidebarLayout from '../components/layouts/sidebar/SidebarLayout';
import { NextPageWithLayout } from './page';
import PrimaryLayout from '@/components/layout/primary/PrimaryLayout';
import SidebarLayout from '@/components/layout/sidebar/SidebarLayout';

export async function getStaticProps() {
  const db = process.env.LOCALHOST
  console.log(db)
  return {
    props: {}, // will be passed to the page component as props
  }
  
  // ...
}

const Home: NextPageWithLayout = () => {
  return (
    <section >
      <PictureCard {...mockPictureCardProps.base} />
    </section>
  );
};
export default Home;

Home.getLayout = (page) => {
  return (
    <PrimaryLayout>
      <SidebarLayout {...mockSidebarLayoutProps.base} />
      {page}
    </PrimaryLayout>
  );
};

// const inter = Inter({ subsets: ['latin'] })

// function PictureList (props: any) {
//   const numbers = props.total
//   const listPicture = numbers.map(() => {
//     <PictureCard {...mockPictureCardProps.base} />
//   })
//   return (
//     <ul>{listPicture}</ul>
//   );
// }

// export default function Home() {
//   const numbers:number[] = [1,2,3]
//   return (
//     <>  
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//       <div style={{ display: 'flex'}}>
//         <PictureCard {...mockPictureCardProps.base} />
//       </div>
//       </main>
//       <footer>
//         <a
//           href="http://localhost:6006/?path=/story/cards-picturecard--base"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//         To update parameter{' '}
//           <span>
//             <Image src="/next.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </>
//   )
// }
